name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/exec conventional-changelog-conventionalcommits

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      # We'll use the checked-in .releaserc.json file instead of creating it dynamically

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fix up the .releaserc.json to avoid shell expansion issues
          sed -i 's/\$\${nextRelease\.version}/\${nextRelease.version}/g' .releaserc.json
          sed -i 's/\$\${nextRelease\.notes}/\${nextRelease.notes}/g' .releaserc.json
          npx semantic-release

  # This job will be triggered by the tag created by semantic-release
  trigger-release:
    name: Trigger Release Workflow
    needs: semantic-release
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10 seconds
        run: sleep 10
        shell: bash

      # No action needed here, the release.yml workflow will be triggered automatically 
      # by the tag created in the semantic-release job
      - name: Notify completion
        run: echo "Semantic release complete. Release workflow should be triggered automatically."