name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/exec conventional-changelog-conventionalcommits

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      # We'll use the checked-in .releaserc.json file instead of creating it dynamically

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          # Fix up the .releaserc.json to avoid shell expansion issues
          sed -i 's/\$\${nextRelease\.version}/\${nextRelease.version}/g' .releaserc.json
          sed -i 's/\$\${nextRelease\.notes}/\${nextRelease.notes}/g' .releaserc.json
          npx semantic-release

  # This job will be triggered by the tag created by semantic-release
  trigger-release:
    name: Trigger Release Workflow
    needs: semantic-release
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Sleep for 10 seconds
        run: sleep 10
        shell: bash
      
      - name: Setup GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh
      
      - name: Verify release and crates.io sync
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the current version from Cargo.toml
          CURRENT_VERSION=$(grep '^version =' Cargo.toml | head -n 1 | cut -d '"' -f 2)
          echo "Latest version from Cargo.toml: $CURRENT_VERSION"
          
          # Check if this version exists on crates.io
          RESPONSE=$(curl -s https://crates.io/api/v1/crates/node-size-analyzer/$CURRENT_VERSION)
          
          if echo "$RESPONSE" | grep -q "\"version\":\"$CURRENT_VERSION\""; then
            echo "Version $CURRENT_VERSION already exists on crates.io. No additional action needed."
          else
            echo "Version $CURRENT_VERSION does not exist on crates.io."
            echo "Triggering GitHub workflow to publish the new version..."
            gh workflow run force-publish.yml -f version=$CURRENT_VERSION
            echo "Workflow triggered. Check GitHub Actions for progress."
          fi
      
      - name: Notify completion
        run: echo "Semantic release complete. Release workflow should be triggered automatically."